apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  labels:
    app: nginx-app
    env: dev 
    type: frontend
spec:
  containers:
    - name: nginx-container
      image: registry.k8s.io/nginx:latest
      ports:
        - containerPort: 80