apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
 labels:
   app: nginx-deployment
   env: dev
spec:
 replicas: 3 #--> Capacity --> running
 selector:
   matchLabels:
     app: nginx-app 
 template:
   metadata:
     name: pod-nginx
     labels:
       app: nginx-app
       env: dev
       type: frontend
   spec:
     containers: 
        - name: nginx-container
          image: gauridocker777/devops:v1
          ports:
            - containerPort: 80